
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://localhost:1433;databaseName=HeThongQuanLyCaLamViec;encrypt=true;trustServerCertificate=true;
db.user=sa
db.password=DIEN_MAT_KHAU_CUA_BAN
